import type { ContentItem } from '@/lib/types';

export const mockData: ContentItem[] = [
  {
    id: 'novel-1',
    title: 'Chương 1: Bình Minh Mới',
    description: 'Một thế giới mới mở ra, đầy hứa hẹn và cũng đầy rẫy những hiểm nguy không lường trước được.',
    category: 'novels',
    date: '2023-10-26',
    content: 'Nội dung chi tiết của chương 1...',
    type: 'text',
    imageUrl: 'https://picsum.photos/seed/novel1/600/400',
  },
  {
    id: 'large-proj-1',
    title: 'Hệ Thống Quản Lý E-commerce',
    description: 'Dự án xây dựng một nền tảng thương mại điện tử hoàn chỉnh với Next.js và Firebase.',
    category: 'large-projects',
    date: '2024-01-15',
    content: 'console.log("Initializing e-commerce project...");',
    type: 'code',
    language: 'javascript',
    imageUrl: 'https://picsum.photos/seed/ecom1/600/400',
    link: 'https://github.com'
  },
  {
    id: 'small-proj-1',
    title: 'Landing Page cho Startup',
    description: 'Thiết kế và triển khai landing page sử dụng HTML, CSS và JS thuần.',
    category: 'small-projects',
    date: '2023-11-20',
    content: '<h1>Welcome to our Startup!</h1>',
    type: 'code',
    language: 'html',
    imageUrl: 'https://picsum.photos/seed/startup1/600/400',
  },
  {
    id: 'fun-code-1',
    title: 'Rắn Săn Mồi Bằng Python',
    description: 'Một trò chơi rắn săn mồi cổ điển được viết bằng Python và Pygame.',
    category: 'fun-code',
    date: '2023-05-30',
    content: 'import pygame\n\n# Game logic here',
    type: 'code',
    language: 'python',
    imageUrl: 'https://picsum.photos/seed/snake1/600/400',
  },
  {
    id: 'idea-1',
    title: 'Ứng dụng theo dõi thói quen',
    description: 'Ý tưởng về một ứng dụng di động giúp người dùng xây dựng và duy trì các thói quen tốt.',
    category: 'ideas',
    date: '2024-03-10',
    content: 'Giao diện đơn giản, tập trung vào việc check-in hàng ngày và thống kê tiến độ.',
    type: 'text',
    imageUrl: 'https://picsum.photos/seed/habit1/600/400',
  },
  {
    id: 'account-1',
    title: 'Thông tin Github',
    description: 'Lưu trữ token và các thông tin cấu hình liên quan đến tài khoản Github.',
    category: 'account',
    date: '2023-01-01',
    content: 'Token: ghp_xxxxxxxxxxxxxxxxxxxx',
    type: 'text',
  },
    {
    id: 'exception-1',
    title: 'Thư mục tài liệu tham khảo',
    description: 'Tổng hợp các link, file và tài liệu hay đã sưu tầm được trong quá trình làm việc.',
    category: 'exceptions',
    date: '2024-02-22',
    content: 'Folder containing various reference materials.',
    type: 'text',
    imageUrl: 'https://picsum.photos/seed/ref1/600/400',
    link: 'https://example.com/folder'
  },
  {
    id: 'large-proj-2',
    title: 'Digital Folio App',
    description: 'Chính là dự án này. Nơi lưu trữ toàn bộ thông tin và các dự án đã thực hiện.',
    category: 'large-projects',
    date: '2024-05-20',
    content: 'You are looking at it!',
    type: 'text',
    imageUrl: 'https://picsum.photos/seed/folio2/600/400',
    link: 'https://github.com'
  },
];
