// This file is automatically generated. Do not edit.
const firebaseConfig = {
  apiKey: "YOUR_API_KEY",
  authDomain: "studio-6431704675-6ab18.firebaseapp.com",
  projectId: "studio-6431704675-6ab18",
  storageBucket: "studio-6431704675-6ab18.appspot.com",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
  appId: "YOUR_APP_ID"
};
export default firebaseConfig;
