// This file is automatically generated. Do not edit.
const firebaseConfig = {
  apiKey: "AIzaSyBHjMCwvNeX8w9n3M4bJ3KdarkybZsf83o",
  authDomain: "studio-6431704675-6ab18.firebaseapp.com",
  projectId: "studio-6431704675-6ab18",
  storageBucket: "studio-6431704675-6ab18.appspot.com",
  messagingSenderId: "806000673656",
  appId: "1:806000673656:web:fe09f249bac4332c23be8d"
};
export default firebaseConfig;
